---
- name: 'Create file'
  become: true
  hosts: all
  tasks:
    - name: 'Copy blog file'
      copy:
        src: /usr/src/condition/blog.txt
        dest: /opt/condition
        owner: bob
        group: bob
        mode: '0640'
      when: 'ansible_host == "node01"'
    - name: 'Copy story file'
      copy:
        src: /usr/src/condition/story.txt
        dest: /opt/condition
        owner: sam
        group: sam
        mode: '0400'
      when: 'ansible_host == "node02"'

# Suggested solution
---
- hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions on node01
      copy:
        src: /usr/src/condition/blog.txt
        dest: /opt/condition/blog.txt
        owner: bob
        group: bob
        mode: "0640"
      when: inventory_hostname == "node01"

    - name: Copy file with owner and permissions on node02
      copy:
        src: /usr/src/condition/story.txt
        dest: /opt/condition/story.txt
        owner: sam
        group: sam
        mode: "0400"
      when: inventory_hostname == "node02"      