---
- name: 'Install required packages'
  become: true
  hosts: localhost
  connection: local
  tasks:
    - yum:
        name: 'vim-enhanced'
        state: present

# Suggested solution
---
- name: 'Install the required package'
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - yum: 
        name: vim-enhanced
        state: present        