---
- name: 'web_nodes'
  hosts: all
  become: yes
  tasks:
    - yum:
        name: 'vsftpd'
        state: present
    - name: 'Start vsftpd service'
      service:
        name: 'vsftpd'
        state: 'started'

# Suggested solution
---
- hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum: name=vsftpd state=installed

  - name: Start service
    service:
      name: vsftpd
      state: started        